name: CI - DB - Staging

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflows }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy Staging DB"
    environment: AWS Staging DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
        with:
          version: 7.27.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run staging migration
        run: pnpm run migration:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
